version: "3"

services:
  ctexpress:
    networks:
      - default
    build: .
    ports:
      - "8080:8080"
  database:
    env_file:
      - .env
    networks:
      - default
    image: mysql:latest
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - default
    depends_on:
      - database
    ports:
      - 1488:80
    environment:
      PMA_HOST: database

networks:
  default:
    driver: host
